package com.life.demo.model;

public class Register {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REGISTER.ID
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REGISTER.NAME
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REGISTER.PASSWORD
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REGISTER.GMT_CREATE
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REGISTER.GMT_MODIFIED
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REGISTER.AVATAR_URL
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    private String avatarUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REGISTER.ID
     *
     * @return the value of REGISTER.ID
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REGISTER.ID
     *
     * @param id the value for REGISTER.ID
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REGISTER.NAME
     *
     * @return the value of REGISTER.NAME
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REGISTER.NAME
     *
     * @param name the value for REGISTER.NAME
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REGISTER.PASSWORD
     *
     * @return the value of REGISTER.PASSWORD
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REGISTER.PASSWORD
     *
     * @param password the value for REGISTER.PASSWORD
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REGISTER.GMT_CREATE
     *
     * @return the value of REGISTER.GMT_CREATE
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REGISTER.GMT_CREATE
     *
     * @param gmtCreate the value for REGISTER.GMT_CREATE
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REGISTER.GMT_MODIFIED
     *
     * @return the value of REGISTER.GMT_MODIFIED
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REGISTER.GMT_MODIFIED
     *
     * @param gmtModified the value for REGISTER.GMT_MODIFIED
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REGISTER.AVATAR_URL
     *
     * @return the value of REGISTER.AVATAR_URL
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REGISTER.AVATAR_URL
     *
     * @param avatarUrl the value for REGISTER.AVATAR_URL
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }
}