package com.life.demo.mapper;

import com.life.demo.model.CommentModel;
import com.life.demo.model.CommentModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CommentModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    long countByExample(CommentModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    int deleteByExample(CommentModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    int insert(CommentModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    int insertSelective(CommentModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    List<CommentModel> selectByExampleWithRowbounds(CommentModelExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    List<CommentModel> selectByExample(CommentModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    CommentModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") CommentModel record, @Param("example") CommentModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    int updateByExample(@Param("record") CommentModel record, @Param("example") CommentModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    int updateByPrimaryKeySelective(CommentModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    int updateByPrimaryKey(CommentModel record);
}