package com.life.demo.mapper;

import com.life.demo.model.Register;
import com.life.demo.model.RegisterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RegisterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REGISTER
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    long countByExample(RegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REGISTER
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    int deleteByExample(RegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REGISTER
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REGISTER
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    int insert(Register record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REGISTER
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    int insertSelective(Register record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REGISTER
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    List<Register> selectByExampleWithRowbounds(RegisterExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REGISTER
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    List<Register> selectByExample(RegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REGISTER
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    Register selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REGISTER
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") Register record, @Param("example") RegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REGISTER
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    int updateByExample(@Param("record") Register record, @Param("example") RegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REGISTER
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    int updateByPrimaryKeySelective(Register record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REGISTER
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    int updateByPrimaryKey(Register record);
}