package com.life.demo.mapper;

import com.life.demo.model.UserModel;
import com.life.demo.model.UserModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    long countByExample(UserModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    int deleteByExample(UserModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    int insert(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    int insertSelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    List<UserModel> selectByExampleWithRowbounds(UserModelExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    List<UserModel> selectByExample(UserModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    UserModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserModel record, @Param("example") UserModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    int updateByExample(@Param("record") UserModel record, @Param("example") UserModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    int updateByPrimaryKeySelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbg.generated Thu Feb 06 13:36:03 CST 2020
     */
    int updateByPrimaryKey(UserModel record);
}